name: Deploy docs

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Cache Next.js build
        id: cache_next_build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.tsx', '**/*.json', '**/*.mdx') }}
          restore-keys: |
            next-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out

  deploy:
    defaults:
      run:
        working-directory: ./docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4